services:
  postgres:
    container_name: 'database'
    image: 'postgres:17.0'
    environment:
      - 'POSTGRES_DB=hom8'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    networks:
      - hom8-net

  rabbitmq:
    container_name: 'rabbit-mq'
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=rabbit'
      - 'RABBITMQ_DEFAULT_USER=rabbit'
    ports:
      - '5672:5672'
    networks:
      - hom8-net

  redis:
    container_name: 'redis'
    image: 'redis:latest'
    ports:
      - '6379:6379'
    networks:
      - hom8-net

networks:
  hom8-net:
    driver: bridge